### ISSUE TITLE
Undo last delete button

### ISSUE THREAD

**Issue by GermaVinsmoke** [GermaVinsmoke/bmi-calculator#4]
Add a undo button which can undo the last deleted item, it can be done by storing the data of the last deleted item in localstorage and if someone clicks on it then it will be added in the main data object.

**Comment by GermaVinsmoke** [comment]
@CmdEngineer @agarwalamn After deleting the last card, undo button is also gone. So can we do anything about that?

**Comment by agarwalamn** [comment]
@GermaVinsmoke checkout pull request also added min and max value that can be added in form data
